<?php

return [
    'services' => [
        "Adult Behavioral Services",
        "Amputee Clinic",
        "Cancer Care",
        "Appointments",
        "Arts in Medicine",
        "Brain Cancer",
        "Breast Cancer",
        "Breast Cancer Helpline",
        "Cervical Cancer",
        "Clinical Trials",
        "Clinical Trials and Costs",
        "Current Trials",
        "DaVinci Robotic Assisted Surgery",
        "Education and Prevention",
        "Diagnostics",
        "Library",
        "Screenings",
        "Side Effects",
        "Emergencies",
        "Financial Information",
        "Intrabeam ® IORT",
        "Lung Cancer",
        "New Patients",
        "Nutrition",
        "Ovarian Cancer",
        "Personalized Cancer Care",
        "Prescriptions Refills",
        "Prostate Cancer",
        "Quit Smoking",
        "Screening Center of Excellence",
        "Skin Cancer",
        "Surgical Oncology",
        "Cancer Screenings",
        "Cardiac and Pulmonary Rehabilitation",
        "Cardiology",
        "Care For Women",
        "Center for Family & Sports Medicine",
        "Child & Adolescent Behavioral Services",
        "Continuing Care",
        "Care at Home",
        "Hospice Care",
        "Give to Hospice",
        "Grief and Bereavement Services",
        "Diabetes Education & Prevention",
        "Emergency Services",
        "Endocrinology",
        "Eye Care",
        "Family Medicine Residency Program",
        "General Surgery",
        "Halifax Health Foundation",
        "Hand Surgery",
        "Healthy Living Centers",
        "Heart and Vascular",
        "Coronary Artery Bypass Surgery",
        "Heart Valve Surgery",
        "Transcatheter Aortic Valve Replacement (TAVR)",
        "Vascular Surgery",
        "Human Resources",
        "Apprenticeship Program",
        "Education to Employment",
        "RN Residency Program",
        "Student Nurse Internship Program",
        "Hyperbaric Medicine",
        "Intensivist",
        "Labor & Delivery",
        "Laboratory",
        "Lung Care",
        "Lung Screening",
        "Minimally Invasive Cardiac Surgery",
        "Modified Barium Swallow Test",
        "Nephrology",
        "Neurosciences",
        "Neuroradiology",
        "Neurorehabilitation",
        "Neurosurgery",
        "Thrombectomy-Capable Stroke Center",
        "OBGYN Hospitalists",
        "Orthopedics",
        "Pain Medicine",
        "Partnerships",
        "Pediatrics",
        "Plastic Surgery and Aesthetics",
        "Podiatry",
        "Primary Care",
        "Prostate Cancer",
        "Radiology",
        "Rehabilitation",
        "Robotics",
        "Sports Medicine Fellowship",
        "Supportive Care",
        "Surgical Weight Loss",
        "Testimonial Example",
        "Transplant Services",
        "Trauma Surgery",
        "Urgent Care",
        "Urology",
        "Pediatric Urology",
        "Volunteer Opportunities",
        "Volunteer Services",
        "Weight Management",
        "Wellness & Fitness Center",
        "Wound Care & Hyperbaric Medicine"
    ],
    'doctors' => [
        "Jose R. Abando\nMD",
        "Fariya S. Afridi\nMD",
        "Felicitas G. Agana\nMD",
        "John E. Agles\nMD",
        "Abdul Q. Ahmed\nMD",
        "Salman Ahmed\nMD",
        "Shahabuddin Ahmed\nDO",
        "Gregor Alexander\nMD",
        "Edilberto R. Alvarez\nMD",
        "Alvaro R. Alvarez-Farinetti\nMD",
        "Edmund K. Andah\nMD",
        "Murthy V. Andavolu\nMD",
        "Arjun D. Aneja\nMD",
        "Maggie P. Angelica\nMD",
        "Muhammed N. Anwer\nMD",
        "Dinesh Arab\nMD",
        "Jason J. Arellano\nMD",
        "Moema Arruda\nDMD",
        "Amir Asaseh\nMD",
        "Amanda C. Aulls\nMD",
        "Sarah A. Bajorek\nDO",
        "Kristen N. Baker\nMD",
        "Cynthia K. Baldwin\nMD",
        "Ralf R. Barckhausen\nMD",
        "Mark B. Barettella\nMD",
        "Carlin D. Barnes\nMD",
        "Beth A. Bartholomew\nMD",
        "Luke M. Basdeo\nMD",
        "Steven T. Batton\nDO",
        "Carson C. Bauder\nMD",
        "Joel O. Bautista\nMD",
        "Eugene V. Bednov\nMD",
        "Jacqueline M. Bernard\nMD",
        "Janak H. Bhavsar\nMD",
        "Marjorie Bhogal\nMD",
        "David Bhola\nDO",
        "Joseph D. Bianchi\nMD",
        "Louis M. Biga\nMD",
        "David W. Billmeier\nMD",
        "Shelly A. Birch\nMD",
        "Harry H. Black\nMD",
        "Michael B. Black\nMD",
        "Harry H. Blanke III\nMD",
        "Jason E. Blatt\nMD",
        "Kareem Bohsali\nMD",
        "Veronica Bonales\nMD",
        "Joseph J. Boolbol\nMD",
        "John D. Boon IV\nMD",
        "John M. Borzok\nDPM",
        "Alireza Bozorgmanesh\nMD",
        "Richard L. Braithwaite\nMD",
        "Beatrice S. Bratu\nMD",
        "Laurence H. Brenner\nMD",
        "Chad L. Broome-Webster\nMD",
        "James M. Bryan\nMD",
        "Sandra L. Buchanan\nMD",
        "Charles M. Burkett\nMD",
        "Ernesto Bustinza Linares\nMD",
        "John M. Cain\nMD",
        "Nally Calzado-Ricketts\nMD",
        "Jorge L. Cambo\nMD",
        "Francisco J. Camino\nMD",
        "Pamela P. Carbiener\nMD",
        "Oscar F. Carbonell\nMD",
        "John T. Carroll\nMD",
        "Lee J. Cartagena-Negron\nMD",
        "Brian P. Cartwright\nMD",
        "Douglas M. Castellano\nMD",
        "Kenneth L. Cate\nMD",
        "Jennifer L. Chan\nDO",
        "Charles J. Chase\nDO",
        "Mubashir A. Chaudhry\nDMD",
        "Boon Y. Chew\nMD",
        "John R. Chewning\nDO",
        "Prady M. Chudasama\nMD",
        "Tamara R. Clancy\nMD",
        "Theodore Clarfield\nMD",
        "Perrin C. Clark\nMD",
        "Ethan N. Cohen\nMD",
        "Luke Babcock\nMD",
        "Isaiah Cochran\nMD",
        "Garner Boogaerts\nMD",
        "Corey Burns\nDO",
        "Zachary Cetraro\nDO",
        "Rachel Cohen-Shohet\nMD",
        "Mansi Amin\nMD",
        "Hannah Cade\nMD",
        "Mark Bender\nMD, DC",
        "Tiffany Anderson\nMD, MHPE",
        "Elizabeth Bonds\nAPRN"
    ]
];
